name: Build site #scheduled + manually

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 5 * * *" #https://crontab.guru/

jobs:
  Generate-Site:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      
      - name: Run Lume
        run: deno task build
      
      - name: Deploy site to gh-pages    
        uses: peaceiris/actions-gh-pages@v3        
        with:         
             github_token: ${{ secrets.GITHUB_TOKEN }}          
             publish_dir: ./dist          
             user_name: 'github-actions[bot]'         
             user_email: 'github-actions[bot]@users.noreply.github.com'
